[package]
name = "steganos"
version = "0.1.1"
edition = "2018"

default-run = "steganos"


# DEPENDENCIES
[dependencies]
image = "0.23.14"
clap = {version = "2.33.3", features = ["yaml"]}

# CRATES
[[bin]]
name = "steganos"
path = "src/cli/cli.rs"
